name: Validate
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          pip install cfn-lint
      - name: Validate CloudFormation
        run: |
          cfn-lint infra/cloudformation/eks-fixed-arm.json
      - name: Lint Kubernetes YAML
        run: |
          pip install kubeconform
          kubeconform -strict -summary -ignore-filename-pattern 'json$$' k8s

