name: Validate
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3-pip curl tar
          pip install cfn-lint
      - name: Validate CloudFormation (cfn-lint)
        run: cfn-lint infra/cloudformation/eks-fixed-arm.json
      - name: Validate JSON parse
        run: jq empty infra/cloudformation/eks-fixed-arm.json
      - name: Validate Kubernetes YAML (basic schema)
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar -xz kubeconform
          ./kubeconform -strict -summary -ignore-filename-pattern 'json$' k8s
